"""Final production graph for simulation, bag replay, and evaluation."""
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument,ExecuteProcess,IncludeLaunchDescription
from launch.conditions import IfCondition,LaunchConfigurationEquals
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import LaunchConfiguration,PathJoinSubstitution
from launch_ros.actions import Node
from launch_ros.substitutions import FindPackageShare

def generate_launch_description():
 mode=LaunchConfiguration('mode');bag=LaunchConfiguration('bag_path');model=LaunchConfiguration('model_path');config=LaunchConfiguration('system_config');world=PathJoinSubstitution([FindPackageShare('lunabot_gazebo'),'worlds','lunar_world.sdf'])
 args=[DeclareLaunchArgument('mode',default_value='simulation',choices=['simulation','bag_replay','evaluation']),DeclareLaunchArgument('bag_path',default_value=''),DeclareLaunchArgument('model_path',default_value=''),DeclareLaunchArgument('model_config',default_value=''),DeclareLaunchArgument('model_checksum',default_value=''),DeclareLaunchArgument('system_config',default_value=PathJoinSubstitution([FindPackageShare('lunabot_bringup'),'config','goal_system.yaml'])),DeclareLaunchArgument('planner',default_value='semantic_dstar_lite'),DeclareLaunchArgument('world_seed',default_value='101'),DeclareLaunchArgument('goal_id',default_value='north'),DeclareLaunchArgument('illumination',default_value='nominal'),DeclareLaunchArgument('sensor_noise',default_value='nominal'),DeclareLaunchArgument('obstacle_scenario',default_value='none'),DeclareLaunchArgument('trial_output',default_value='evidence/trials/trial.json'),DeclareLaunchArgument('use_rviz',default_value='true')]
 sim_condition=LaunchConfigurationEquals('mode','simulation');sim=IncludeLaunchDescription(PythonLaunchDescriptionSource(PathJoinSubstitution([FindPackageShare('ros_gz_sim'),'launch','gz_sim.launch.py'])),launch_arguments={'gz_args':['-r ',world]}.items(),condition=sim_condition)
 spawn=Node(package='ros_gz_sim',executable='create',arguments=['-file',PathJoinSubstitution([FindPackageShare('lunabot_gazebo'),'models','lunabot_v4','model.sdf']),'-name','lunabot_v4','-z','1.0'],condition=sim_condition,output='screen')
 bridges=Node(package='ros_gz_bridge',executable='parameter_bridge',arguments=['/clock@rosgraph_msgs/msg/Clock[gz.msgs.Clock','/lunabot/camera/image_raw@sensor_msgs/msg/Image[gz.msgs.Image','/lunabot/camera/camera_info@sensor_msgs/msg/CameraInfo[gz.msgs.CameraInfo','/lunabot/depth/image_raw@sensor_msgs/msg/Image[gz.msgs.Image','/lunabot/depth/camera_info@sensor_msgs/msg/CameraInfo[gz.msgs.CameraInfo','/lunabot/lidar/scan@sensor_msgs/msg/LaserScan[gz.msgs.LaserScan','/lunabot/imu@sensor_msgs/msg/Imu[gz.msgs.IMU','/lunabot/odom@nav_msgs/msg/Odometry[gz.msgs.Odometry','/tf@tf2_msgs/msg/TFMessage[gz.msgs.Pose_V','/cmd_vel@geometry_msgs/msg/Twist]gz.msgs.Twist'],condition=sim_condition,output='screen')
 replay=ExecuteProcess(cmd=['ros2','bag','play',bag,'--clock'],output='screen',condition=LaunchConfigurationEquals('mode','bag_replay'))
 nodes=[Node(package='lunabot_perception',executable='terrain_inference_node',name='terrain_inference',parameters=[config,{'model_path':model,'config_path':LaunchConfiguration('model_config'),'checksum_path':LaunchConfiguration('model_checksum')}],output='screen'),Node(package='lunabot_mapping',executable='semantic_fusion_node',parameters=[config],output='screen'),Node(package='lunabot_mapping',executable='traversability_node',parameters=[config],output='screen'),Node(package='lunabot_planning',executable='dstar_lite_planner',parameters=[config],output='screen'),Node(package='lunabot_planning',executable='replan_verifier',parameters=[config],output='screen'),Node(package='lunabot_control',executable='regulated_path_follower',parameters=[config],output='screen'),Node(package='lunabot_control',executable='safety_supervisor',parameters=[config],output='screen'),Node(package='lunabot_evaluation',executable='mission_metrics',parameters=[config,{'trial_output':LaunchConfiguration('trial_output')}],output='screen'),Node(package='rviz2',executable='rviz2',arguments=['-d',PathJoinSubstitution([FindPackageShare('lunabot_bringup'),'rviz','goal_system.rviz'])],condition=IfCondition(LaunchConfiguration('use_rviz')),output='screen')]
 return LaunchDescription(args+[sim,spawn,bridges,replay]+nodes)
